# Generated by Django 4.2.25 on 2025-11-03 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=255)),
                ('max_tokens', models.IntegerField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('additional_model_request_fields', models.JSONField(null=True)),
                ('region_name', models.CharField(max_length=255, null=True)),
                ('prompt_cost', models.FloatField(null=True)),
                ('completion_cost', models.FloatField(null=True)),
                ('cached_write_cost', models.FloatField(null=True)),
                ('cached_read_cost', models.FloatField(null=True)),
                ('provider', models.CharField(choices=[('bedrock', 'Bedrock')], max_length=255, null=True)),
                ('production_model', models.CharField(choices=[('strong', 'Strong'), ('weak', 'Weak'), ('tiny', 'Tiny'), ('embed', 'Embed'), ('thinking', 'Thinking'), ('hybrid', 'Hybrid'), ('agent', 'Agent')], max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prompt', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvokeCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField(null=True)),
                ('completion_tokens', models.IntegerField(null=True)),
                ('prompt_tokens', models.IntegerField(null=True)),
                ('cached_write_tokens', models.IntegerField(null=True)),
                ('cached_read_tokens', models.IntegerField(null=True)),
                ('prompt_cost', models.FloatField(null=True)),
                ('completion_cost', models.FloatField(null=True)),
                ('cached_write_cost', models.FloatField(null=True)),
                ('cached_read_cost', models.FloatField(null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bedrock.model')),
            ],
        ),
    ]
