# Generated by Django 4.2.25 on 2025-11-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0107_migrate_filters_to_rich_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], db_index=True, default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('unstarted', 'Unstarted'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='backlog', max_length=20),
        ),
    ]
