# Generated by Django 4.2.25 on 2025-11-03 02:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import pgvector.django.vector


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret',
                 django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True))),
                ('tenant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_folder', models.CharField(blank=True, max_length=255, null=True)),
                ('folder_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('delta_token', models.TextField(blank=True, null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_callback', models.URLField(blank=True, null=True)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255)),
                ('conversation_id', models.TextField(blank=True)),
                ('received_datetime', models.DateTimeField()),
                ('recipients',
                 django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('subject', models.TextField(blank=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('has_attachments', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleaned_body', models.TextField(null=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails',
                                             to='outlook.emaildatasource')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attachment_id', models.CharField(max_length=255, null=True)),
                ('content_type', models.CharField(max_length=255, null=True)),
                ('inline', models.BooleanField(null=True)),
                ('size', models.IntegerField(null=True)),
                ('processed_sharepoint_link', models.TextField(null=True)),
                ('text_content', models.TextField(null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments',
                                            to='outlook.email')),
            ],
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['conversation_id'], name='conversation_id_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['-received_datetime'], name='received_datetime_desc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together={('source', 'message_id')},
        ),
    ]
