# Generated by Django 4.2.25 on 2025-11-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='classification',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
